create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null,
  image_url text not null,
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text,
  customer_email text,
  customer_phone text,
  notes text,
  status text not null default 'new',
  source text not null default 'aura-build',
  total_amount numeric(10,2) not null default 0,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.subscribers enable row level security;
alter table public.orders enable row level security;

create policy "public can read active featured products"
on public.products
for select
to anon, authenticated
using (active = true);

create policy "public can subscribe"
on public.subscribers
for insert
to anon, authenticated
with check (email is not null);

create policy "public can create orders"
on public.orders
for insert
to anon, authenticated
with check (coalesce(total_amount, 0) >= 0);

create policy "admins can read subscribers"
on public.subscribers
for select
to authenticated
using (
  auth.jwt() ->> 'email' in ('YOUR_ADMIN_EMAIL@example.com')
);

create policy "admins can read orders"
on public.orders
for select
to authenticated
using (
  auth.jwt() ->> 'email' in ('YOUR_ADMIN_EMAIL@example.com')
);

insert into public.products (name, price, image_url, featured, active)
values
  ('BPC-157', 38.00, 'https://qvzavbjhfbovsxtcixld.supabase.co/storage/v1/object/public/product-images/BPC.png', true, true),
  ('GHK-CU', 88.00, 'https://qvzavbjhfbovsxtcixld.supabase.co/storage/v1/object/public/product-images/GHK.png', true, true),
  ('Glow', 128.00, 'https://qvzavbjhfbovsxtcixld.supabase.co/storage/v1/object/public/product-images/GLOW.png', true, true),
  ('Tesamorelin', 98.00, 'https://qvzavbjhfbovsxtcixld.supabase.co/storage/v1/object/public/product-images/Tesa.jpg', true, true)
on conflict do nothing;
